@gateway = http://localhost:8080
@tenantId = 000000
@frontClientId = 7f57f2e3c3f14d15a7c4dd8b7e69a241
@username = front_test_001
@password = 123456

### 前台注册
POST {{gateway}}/auth/front/register
Content-Type: application/json

{
  "tenantId": "{{tenantId}}",
  "username": "{{username}}",
  "password": "{{password}}"
}

### 前台登录
POST {{gateway}}/auth/front/login
Content-Type: application/json

{
  "tenantId": "{{tenantId}}",
  "username": "{{username}}",
  "password": "{{password}}"
}

> {%
client.global.set("front_access_token", response.body.data.accessToken);
%}

### 前台登录后查询我的作品
GET {{gateway}}/music/portal/music/my
ClientId: {{frontClientId}}
Authorization: Bearer {{front_access_token}}

### 前台公开接口校验
GET {{gateway}}/music/open/tag/list
###
POST http://localhost:9211/front/register
Content-Type: application/json

{
    "tenantId": "000000",
    "username": "front_test_001",
    "password": "123456"
}
