# Tomcat
server:
  port: 8080
  servlet:
    context-path: /

# Security
security:
  ignore:
    whites:
      - /**

# Spring
spring:
  application:
    name: ruoyi-gateway
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      requestLog: true
      routes:
        - id: music
          uri: http://hjm-music-web:9212
          predicates:
            - Path=/music/**
          filters:
            - StripPrefix=1
  data:
    redis:
      host: hjm-valkey
      port: 6379
      database: 0

# Sa-Token
sa-token:
  token-name: Authorization
  check-same-token: false
