# 公共数据源变量
datasource:
  system-master:
    url: jdbc:postgresql://hjm-postgres:5432/ry-cloud?currentSchema=public&reWriteBatchedInserts=true
    username: ruoyi
    password: ruoyi123
    driver-class-name: org.postgresql.Driver

spring:
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          url: ${datasource.system-master.url}
          username: ${datasource.system-master.username}
          password: ${datasource.system-master.password}
          driver-class-name: ${datasource.system-master.driver-class-name}
        gen:
          url: ${datasource.system-master.url}
          username: ${datasource.system-master.username}
          password: ${datasource.system-master.password}
          driver-class-name: ${datasource.system-master.driver-class-name}
        job:
          url: ${datasource.system-master.url}
          username: ${datasource.system-master.username}
          password: ${datasource.system-master.password}
          driver-class-name: ${datasource.system-master.driver-class-name}
        workflow:
          url: ${datasource.system-master.url}
          username: ${datasource.system-master.username}
          password: ${datasource.system-master.password}
          driver-class-name: ${datasource.system-master.driver-class-name}
      strict: false
    type: com.zaxxer.hikari.HikariDataSource
