FROM bellsoft/liberica-openjdk-rocky:21.0.8-cds

LABEL maintainer="momao"

RUN mkdir -p /hjm/music/logs \
    /hjm/music/temp

WORKDIR /hjm/music

ENV SERVER_PORT=9212 LANG=C.UTF-8 LC_ALL=C.UTF-8 JAVA_OPTS=""

EXPOSE ${SERVER_PORT}

ADD ./target/hjm-music-web.jar ./app.jar

ENTRYPOINT java -Djava.security.egd=file:/dev/./urandom -Dserver.port=${SERVER_PORT} \
           -XX:+HeapDumpOnOutOfMemoryError -XX:+UseZGC ${JAVA_OPTS} \
           -jar app.jar
