server:
  port: 9206

spring:
  application:
    name: hjm-music
  profiles:
    active: local
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        enabled: false
      config:
        enabled: false
    discovery:
      enabled: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    dynamic:
      primary: system-master
      strict: true
      p6spy: true
      seata: false
      datasource:
        system-master:
          url: jdbc:postgresql://8.148.70.157:5432/ry-cloud?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
          username: postgres
          password: memory1314
#        gen:
#          url: jdbc:postgresql://8.148.70.157:5432/ry-cloud?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
#          username: postgres
#          password: memory1314
#        job:
#          url: jdbc:postgresql://8.148.70.157:5432/ry-job?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
#          username: postgres
#          password: memory1314
#        workflow:
#          url: jdbc:postgresql://8.148.70.157:5432/ry-workflow?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
#          username: postgres
#          password: memory1314
      hikari:
        maxPoolSize: 20
        minIdle: 10
        connectionTimeout: 30000
        validationTimeout: 5000
        idleTimeout: 600000
        maxLifetime: 180000
        keepaliveTime: 30000

  data:
    redis:
      password: memory1314

mybatis-flex:
  check-config-location: false
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  type-aliases-package: org.dromara.**.domain
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: FULL
    auto-mapping-unknown-column-behavior: NONE
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
  global-config:

    print-banner: true
    key-config:
      key-type: Generator
      value: snowFlakeId
    deleted-value-of-logic-delete: "1"
    normal-value-of-logic-delete: "0"

dubbo:
  registry:
    address: N/A
  metadata-report:
    address: N/A
