<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.1.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.1.0 http://maven.apache.org/xsd/maven-4.1.0.xsd">
    <modelVersion>4.1.0</modelVersion>

    <groupId>org.dromara</groupId>
    <artifactId>ruoyi-common-bom</artifactId>
    <version>${revision}</version>
    <packaging>pom</packaging>

    <description>
        ruoyi-common-bom common依赖项
    </description>

    <properties>
    <maven.compiler.release>17</maven.compiler.release>
        <revision>2.5.1</revision>
    </properties>

    <dependencyManagement>
        <dependencies>
            <!-- 核心模块 -->
            <dependency>
                <groupId>org.dromara</groupId>
                <artifactId>ruoyi-common-core</artifactId>
            </dependency>

            <!-- 接口模块 -->
            <dependency>
                <groupId>org.dromara</groupId>
                <artifactId>ruoyi-common-doc</artifactId>
            </dependency>

            <!-- 安全模块 -->
            <dependency>
                <groupId>org.dromara</groupId>
                <artifactId>ruoyi-common-security</artifactId>
            </dependency>

            <!-- 权限认证服务 -->
            <dependency>
                <groupId>org.dromara</groupId>
                <artifactId>ruoyi-common-satoken</artifactId>
            </dependency>

            <!-- 日志记录 -->
            <dependency>
                <groupId>org.dromara</groupId>
                <artifactId>ruoyi-common-log</artifactId>
            </dependency>

            <!-- 通用service实现模块 -->
            <dependency>
                <groupId>org.dromara</groupId>
                <artifactId>ruoyi-common-service-impl</artifactId>
            </dependency>

            <!-- excel -->
            <dependency>
                <groupId>org.dromara</groupId>
                <artifactId>ruoyi-common-excel</artifactId>
            </dependency>

            <!-- 缓存服务 -->
            <dependency>
                <groupId>org.dromara</groupId>
                <artifactId>ruoyi-common-redis</artifactId>
            </dependency>

            <!-- web服务 -->
            <dependency>
                <groupId>org.dromara</groupId>
                <artifactId>ruoyi-common-web</artifactId>
            </dependency>

            <!-- 数据库服务 -->
            <dependency>
                <groupId>org.dromara</groupId>
                <artifactId>ruoyi-common-mybatis</artifactId>
            </dependency>
            <dependency>
                <groupId>org.dromara</groupId>
                <artifactId>hjm-mybatis-flex</artifactId>
            </dependency>

            <!-- 定时任务 -->
            <dependency>
                <groupId>org.dromara</groupId>
                <artifactId>ruoyi-common-job</artifactId>
            </dependency>

            <!-- RPC服务 -->
            <dependency>
                <groupId>org.dromara</groupId>
                <artifactId>ruoyi-common-dubbo</artifactId>
            </dependency>

            <!-- 分布式事务 -->
            <dependency>
                <groupId>org.dromara</groupId>
                <artifactId>ruoyi-common-seata</artifactId>
            </dependency>

            <!-- 自定义负载均衡 -->
            <dependency>
                <groupId>org.dromara</groupId>
                <artifactId>ruoyi-common-loadbalancer</artifactId>
            </dependency>

            <!-- oss服务 -->
            <dependency>
                <groupId>org.dromara</groupId>
                <artifactId>ruoyi-common-oss</artifactId>
            </dependency>

            <!-- 限流功能 -->
            <dependency>
                <groupId>org.dromara</groupId>
                <artifactId>ruoyi-common-ratelimiter</artifactId>
            </dependency>

            <!-- 幂等功能 -->
            <dependency>
                <groupId>org.dromara</groupId>
                <artifactId>ruoyi-common-idempotent</artifactId>
            </dependency>

            <!-- 邮件模块 -->
            <dependency>
                <groupId>org.dromara</groupId>
                <artifactId>ruoyi-common-mail</artifactId>
            </dependency>

            <!-- 短信模块 -->
            <dependency>
                <groupId>org.dromara</groupId>
                <artifactId>ruoyi-common-sms</artifactId>
            </dependency>

            <!-- logstash日志推送模块 -->
            <dependency>
                <groupId>org.dromara</groupId>
                <artifactId>ruoyi-common-logstash</artifactId>
            </dependency>

            <!-- ES搜索引擎服务 -->
            <dependency>
                <groupId>org.dromara</groupId>
                <artifactId>ruoyi-common-elasticsearch</artifactId>
            </dependency>

            <!-- skywalking日志收集模块 -->
            <dependency>
                <groupId>org.dromara</groupId>
                <artifactId>ruoyi-common-skylog</artifactId>
            </dependency>

            <!-- prometheus监控 -->
            <dependency>
                <groupId>org.dromara</groupId>
                <artifactId>ruoyi-common-prometheus</artifactId>
            </dependency>

            <!-- 通用翻译功能 -->
            <dependency>
                <groupId>org.dromara</groupId>
                <artifactId>ruoyi-common-translation</artifactId>
            </dependency>

            <!-- 脱敏模块 -->
            <dependency>
                <groupId>org.dromara</groupId>
                <artifactId>ruoyi-common-sensitive</artifactId>
            </dependency>

            <!-- 序列化模块 -->
            <dependency>
                <groupId>org.dromara</groupId>
                <artifactId>ruoyi-common-json</artifactId>
            </dependency>

            <!-- 数据加解密模块 -->
            <dependency>
                <groupId>org.dromara</groupId>
                <artifactId>ruoyi-common-encrypt</artifactId>
            </dependency>

            <!-- 租户模块 -->
            <dependency>
                <groupId>org.dromara</groupId>
                <artifactId>ruoyi-common-tenant</artifactId>
            </dependency>

            <!-- websocket模块 -->
            <dependency>
                <groupId>org.dromara</groupId>
                <artifactId>ruoyi-common-websocket</artifactId>
            </dependency>

            <!-- 授权认证 -->
            <dependency>
                <groupId>org.dromara</groupId>
                <artifactId>ruoyi-common-social</artifactId>
            </dependency>

            <!-- 配置中心 -->
            <dependency>
                <groupId>org.dromara</groupId>
                <artifactId>ruoyi-common-nacos</artifactId>
            </dependency>

            <!-- 消息总线模块 -->
            <dependency>
                <groupId>org.dromara</groupId>
                <artifactId>ruoyi-common-bus</artifactId>
            </dependency>

            <!-- sse -->
            <dependency>
                <groupId>org.dromara</groupId>
                <artifactId>ruoyi-common-sse</artifactId>
            </dependency>

        </dependencies>
    </dependencyManagement>
</project>
